name = "laptop-rhel84"
description = "Laptop RHEL8 OSTress BaseImage"
version = "1.0.13"
modules = []
groups = []

distro = "rhel-84"

[[packages]]
name = "podman"
version = "*"

[[packages]]
name = "net-tools"
version = "*"

[[packages]]
name = "vim-enhanced"
version = "*"

[[packages]]
name = "dhcp-server"
version = "*"

[[packages]]
name = "httpd"
version = "*"

[[packages]]
name = "cockpit"
version = "*"

[[containers]]
source = "rhde-dev9.bcnconsulting.com:5000/2048:prod"
tls-verify = false

[customizations]
hostname = "baseimage"

[customizations.timezone]
timezone = "Europe/Madrid"

[[customizations.user]]
name = "admin"
password = "$6$ixxxxxxxxYYYYYYYYzzzzzzZZ"
groups = ["users", "wheel"]

[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "es"

[customizations.firewall.services]
enabled = ["http", "https", "dhcp"]
disabled = ["telnet"]

[customizations.services]
enabled = ["sshd", "cockpit.socket", "dhcpd"]
disabled = ["postfix", "telnetd"]

[[customizations.files]]
path = "/etc/dhcp/dhcpd.conf"
mode = "0644"
user = "root"
group = "root"
data = """
#
# DHCP Server Configuration file.
#   see /usr/share/doc/dhcp-server/dhcpd.conf.example
#   see dhcpd.conf(5) man page
#
option architecture-type code 93 = unsigned integer 16;

subnet 192.168.40.0 netmask 255.255.255.0 {
  option routers 192.168.40.2;
  option domain-name-servers 192.168.40.2;
  range 192.168.40.150 192.168.40.200;
  class "pxeclients" {
    match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";
    next-server 192.168.40.1;
          if option architecture-type = 00:07 {
            filename "redhat/EFI/BOOT/BOOTX64.EFI";
          }
          else {
            filename "pxelinux/pxelinux.0";
          }
  }
  class "httpclients" {
    match if substring (option vendor-class-identifier, 0, 10) = "HTTPClient";
    option vendor-class-identifier "HTTPClient";
    filename "http://192.168.40.2/rhel84/EFI/BOOT/BOOTX64.EFI";
  }
}
"""
