name = "rhel84-nvidia"
description = "Blueprint for Edge rhel84 and nvidia"
version = "0.0.13"
modules = []
groups = []
distro = "rhel-8.4"

[[packages]]
name = "glibc-langpack-en"
version = "*"

[[packages]]
name = "podman"
version = "*"

[[packages]]
name = "net-tools"
version = "*"

[[packages]]
name = "bind-utils"
version = "*"

[[packages]]
name = "vim"
version = "*"

[[packages]]
name = "nmap"
version = "*"

[[packages]]
name = "vim-enhanced"
version = "*"

[[packages]]
name = "git"
version = "*"

[[packages]]
name = "nvidia-fabric-manager"
version = "470.161.03"

[[packages]]
name = "libnvidia-nscq-470"
version = "470.161.03"

[[packages]]
name = "nvidia-container-toolkit"
version = "*"

[[packages]]
name = "container-selinux.noarch"
version = "*"

[[packages]]
name = "nvidia-driver-cuda"
version = "470.161.03"

[customizations]
hostname = "baseimage1"

[[customizations.user]]
name = "admin"
password = "$6$Q4FN9N4qP1Yqfev1$F.ovvDXjb4M.Vw0kSyCPBZKqemA00A7fQBaEgan78pjGOd9wPkjeLG2FZXijx/PJ4JOY1BRWbcxnFvb3PtmQP0"
groups = ["users", "wheel"]
[customizations.timezone]
timezone = "Europe/Madrid"
[customizations.locale]
languages = ["en_US.UTF-8"]
keyboard = "es"
